# Generated by Django 3.0.3 on 2020-02-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=10000)),
                ('writer', models.CharField(max_length=10)),
                ('writer_ip', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(max_length=10)),
                ('post_hit', models.IntegerField()),
            ],
        ),
    ]
