# Generated by Django 3.0.3 on 2020-02-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='post_hit',
            field=models.IntegerField(default=0),
        ),
    ]
