# Generated by Django 3.0.3 on 2020-02-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_delete_uploadfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='thumbnail',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
